apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: mariadb
type: Opaque
stringData:
  # Using stringData allows plain text values (Kubernetes will base64 encode them automatically)
  mysql-root-password: rootpassword
  mysql-database: springboot
  mysql-user: springboot_user
  mysql-password: springboot_password
  datasource-url: jdbc:mariadb://mariadb:3306/springboot
  datasource-username: root
  datasource-password: rootpassword
