apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-metrics
  namespace: default
  labels:
    app: springboot-backend
    prometheus: "true"
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-backend
  type: ClusterIP
---
# Note: ServiceMonitor requires Prometheus Operator
# For basic Prometheus setup, we use pod discovery instead
# This service is created for future use with Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-backend
  namespace: monitoring
  labels:
    app: springboot-backend
spec:
  selector:
    matchLabels:
      prometheus: "true"
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s
